[book]
authors = ["Septs", "yunwei37", "ocfox"]
language = "en"
multilingual = false
src = "src"
title = "Eunomia-bpf Documents"

[output.html]
git-repository-url = "https://github.com/eunomia-bpf/eunomia-bpf"
git-repository-icon = "fa-github"

[output.html.fold]
enable = true

[output.linkcheck]
follow-web-links = true

exclude = [ 'openai.com', 'geekbang.org', 'aliyun.com' ]
